import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  LoginGuardGuard,
 // LoginRGuardGuard,
  AltaFacturasGuard,
  RolesGuard,
  UserOptionsGuard,
  VerUsuariosGuard,
  PrivilegiosUsuariosGuard,
  ParametrosGuard,
  OptionsGuard,
  UsuariosCadenasGuard,
  ListasGuard,
  RolesOptionsGuard,
  AltaContribuyentesGuard,
  MantenimientoContribuyentesGuard,
  AltaSolicitudesGuard,
  EstatusSolicitudesGuard,
  ReporteFacturasGuard,
  ReporteDiarioGuard,
  ReporteBancosGuard,
  ReportePagosCompanyGuard,
  ReporteFacturasDetallesGuard,
  ReporteSolicitudesGuard,
  ReporteSolicitudesDetallesGuard,
  ReportecfdisGuard,
  ReporteDirectorGuard,
  ReporteSolicitudesFondeoGuard,
  ProyectosProveedoresGuard,
  PagosProveedorGuard,
  PagosCadenaGuard,
  TarifasGuard,
  AltacypGuard,
  UsuariosProveedoresGuard,
  ContribuyentesFundersGuard,
  SolicituddeFondeoGuard,
  PagosafinancieraGuard,
  PagosafondeadorGuard,

  SettingsService,
  SidebarService,
  SharedService,
  UsuarioService,
  PrivilegiosUsuariosService,
  RolesService,
  ParametrosGeneralesService,
  OptionsService,
  UserOptionsService,
  ListasService,
  RolesOptionsService,
  ContribuyentesService,
  AltaSolicitudesService,
  ReportesService,
  PagosService,
  DashboardService,
  TarifasService,
  FacturasService,
  MantenimientoContribuyentesService,
  FundersService,
  MiFielService,
  GuardService,
  ReportesPDFService
 } from './service.index';


@NgModule({
  imports: [
    CommonModule,
    HttpClientModule
  ],
  providers: [
    LoginGuardGuard,
   // LoginRGuardGuard,
    AltaFacturasGuard,
    RolesGuard,
    UserOptionsGuard,
    VerUsuariosGuard,
    PrivilegiosUsuariosGuard,
    ParametrosGuard,
    OptionsGuard,
    UsuariosCadenasGuard,
    ListasGuard,
    RolesOptionsGuard,
    AltaContribuyentesGuard,
    MantenimientoContribuyentesGuard,
    AltaSolicitudesGuard,
    EstatusSolicitudesGuard,
    ReporteFacturasGuard,
    ReporteDiarioGuard,
    ReporteBancosGuard,
    ReportePagosCompanyGuard,
    ReporteFacturasDetallesGuard,
    ReporteSolicitudesGuard,
    ReporteSolicitudesDetallesGuard,
    ReportecfdisGuard,
    ReporteDirectorGuard,
    ReporteSolicitudesFondeoGuard,
    ProyectosProveedoresGuard,
    PagosProveedorGuard,
    PagosCadenaGuard,
    TarifasGuard,
    AltacypGuard,
    UsuariosProveedoresGuard,
    ContribuyentesFundersGuard,
    SolicituddeFondeoGuard,
    PagosafinancieraGuard,
    PagosafondeadorGuard,

    SettingsService,
    SidebarService,
    SharedService,
    UsuarioService,
    PrivilegiosUsuariosService,
    RolesService,
    ParametrosGeneralesService,
    OptionsService,
    UserOptionsService,
    ListasService,
    RolesOptionsService,
    ContribuyentesService,
    AltaSolicitudesService,
    ReportesService,
    PagosService,
    DashboardService,
    TarifasService,
    FacturasService,
    MantenimientoContribuyentesService,
    FundersService,
    MiFielService,
    GuardService,
    ReportesPDFService
  ],
  declarations: []
})
export class ServiceModule { }
